### PR TITLE
Lost messages into M3UA part. The need for aspTrafficListener

### PR DESCRIPTION
**Pull request by Oleg-Afanasiev**
Hello,

This PR contains the implementation of problems described in issue #145.
Please review the implementation and let's discuss it.

Thanks,
Oleg Afanasiev

### CODE REVIEW

**Comment by deruelle** [comment]
@Oleg-Afanasiev it looks like the branch has conflicts, can you make sure to rebase against the current master ?

**Comment by deruelle** [comment]
Thanks @Oleg-Afanasiev. @vetss can you review ?

**Comment by Oleg-Afanasiev** [comment]
Ty for comment. I made pull request from old version, but now I resolved branch conflicts.

**Comment by vetss** [comment]
I have committed your updates as a solid commit into a master branch.

**Pull request closed without merging**
