### PR TITLE
Tag#7.1.1383 issue#77 cap callgap

### PR DESCRIPTION
**Pull request by bkrok**
Call gap extension to CAP

Call gap may be applied due to near-overload condition occurring in TelScale. Particular services running on JSLEE shall detect the overload condition and trigger CallGap as required.

### CODE REVIEW

**Comment by vetss** [comment]
Hello @bkrok 

we can not accept "New release candidate" commit because it afffects pom versions so we can not do so.
I will to try to make cherry pick for another update, check it and (if it is ok) commit to master branch.
Thanks for your work.

**Comment by vetss** [comment]
@bkrok 
Ops, I see you closed this PR. Are you going to create a new one ?

**Comment by bkrok** [comment]
Hello,

I started this functionality from commit 4705f72 and 7.0.1383 tag. I have created a new branch with correct tag name and I will create a new PR to master branch. 
We have also others features to contribute. If it is possible to create new branch from mentioned commit we can pull all features to this one.

**Comment by vetss** [comment]
You need to create you development branch from master branch of jss7 repo and put there your update. Then you can make cherry pick of your commit for example and then make a new pull request.

**Pull request closed without merging**
